### ISSUE TITLE
Pychromecast API has changed

### ISSUE THREAD

**Issue by ghost** [KeizerDev/Rhythmbox-Chromecast#10]
It seems like this plugin isn't maintained anymore, but for anyone trying to install it on a newer version of Ubuntu/other distro, there are a few things that have changed in the pychromecast API.

They are all clearly spelled out in the traceback:
```Traceback (most recent call last):
  File "/home/amr/.local/share/rhythmbox/plugins/chromecast/Chromecast.py", line 33, in do_activate
    self.source.setup()
  File "/home/amr/.local/share/rhythmbox/plugins/chromecast/ChromecastSource.py", line 49, in setup
    self.chromecast = pychromecast.get_chromecast(friendly_name=Prefs.chromecastName)
AttributeError: module 'pychromecast' has no attribute 'get_chromecast'
Traceback (most recent call last):
  File "/home/amr/.local/share/rhythmbox/plugins/chromecast/Chromecast.py", line 39, in do_deactivate
    self.source.uninstall()
  File "/home/amr/.local/share/rhythmbox/plugins/chromecast/ChromecastSource.py", line 85, in uninstall
    self.server.shutdown()
AttributeError: 'ChromecastSource' object has no attribute 'server'
Traceback (most recent call last):
  File "/home/amr/.local/share/rhythmbox/plugins/chromecast/Chromecast.py", line 33, in do_activate
    self.source.setup()
  File "/home/amr/.local/share/rhythmbox/plugins/chromecast/ChromecastSource.py", line 49, in setup
    self.chromecast = pychromecast.get_chromecast(friendly_name=Prefs.chromecastName)
AttributeError: module 'pychromecast' has no attribute 'get_chromecast'```

Fixing these will probably actually be quite easy, and if I can find the time I will try and fix it and submit a pull request. If the dev doesn't check this account anymore I will post a link to my fork here.

**Comment by KeizerDev** [comment]
Pr is welcome :)
