### ISSUE TITLE
Can't build wheels

### ISSUE THREAD

**Issue by PowerUser64** [KeizerDev/Rhythmbox-Chromecast#13]
Whenever I run `pip install -r requirements.txt`, I get the following errors (preceded by good output). Not sure what to do.
If somone could help me out, I'm sure it's some simple solution.
```
Building wheels for collected packages: casttube, ifaddr
  Running setup.py bdist_wheel for casttube ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-OA8G1x/casttube/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpI1sM9Vpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for casttube
  Running setup.py clean for casttube
  Running setup.py bdist_wheel for ifaddr ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-OA8G1x/ifaddr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpNBtp_jpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for ifaddr
  Running setup.py clean for ifaddr
Failed to build casttube ifaddr
Installing collected packages: urllib3, certifi, chardet, idna, requests, casttube, six, setuptools, protobuf, typing, ipaddress, ifaddr, zeroconf, pychromecast
  Running setup.py install for casttube ... done
  Running setup.py install for ifaddr ... done
Successfully installed casttube-0.2.0 certifi-2019.3.9 chardet-3.0.4 idna-2.8 ifaddr-0.1.6 ipaddress-1.0.22 protobuf-3.7.1 pychromecast-3.0.0 requests-2.21.0 setuptools-40.8.0 six-1.12.0 typing-3.6.6 urllib3-1.24.1 zeroconf-0.21.3
```

**Comment by KeizerDev** [comment]
Try `pip install wheel` and then run the `pip install -r requirements.txt` again

**Comment by PowerUser64** [comment]
Yay! That worked. Thanks a lot!

**Comment by PowerUser64** [comment]
Okay...
Now, I'm getting a failed to load error from Rhythmbox when I try to load the plugin.

**Comment by PowerUser64** [comment]
![Failed to load](https://user-images.githubusercontent.com/24578572/55059032-15bc7980-502b-11e9-94ba-7056686afd50.png)

**Comment by KeizerDev** [comment]
Can you open Rhythmbox using you the terminal? So you can see what's going on?

**Comment by PowerUser64** [comment]
This is the error:
```
(rhythmbox:25449): libpeas-WARNING **: 01:10:54.981: Error importing plugin 'Chromecast':
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blakely/.local/share/rhythmbox/plugins/chromecast/Chromecast.py", line 9, in <module>
    import ChromecastSource
  File "/home/blakely/.local/share/rhythmbox/plugins/chromecast/ChromecastSource.py", line 4, in <module>
    import pychromecast
ModuleNotFoundError: No module named 'pychromecast'
```

**Comment by KeizerDev** [comment]
Yeah so pychromecast is not installed. It says it uses python3.6 so you should try to do `pip3.6 install pychromecast`

**Comment by PowerUser64** [comment]
Okay. It has been successfully installed. Now I've just gotta configure Prefs.py.
Thanks for your help and time!
