### ISSUE TITLE
'pychromecast' has no attribute 'get_chromecast'

### ISSUE THREAD

**Issue by PowaBanga** [KeizerDev/Rhythmbox-Chromecast#16]
Hi everybody,
it seem that the plugin do not work for me...
```
Traceback (most recent call last):
  File "/home/powabanga/.local/share/rhythmbox/plugins/chromecast/Chromecast.py", line 33, in do_activate
    self.source.setup()
  File "/home/powabanga/.local/share/rhythmbox/plugins/chromecast/ChromecastSource.py", line 49, in setup
    self.chromecast = pychromecast.get_chromecast(friendly_name=Prefs.chromecastName)
AttributeError: module 'pychromecast' has no attribute 'get_chromecast'

```
Does anybody can help me to fix that ?

**Comment by KeizerDev** [comment]
Thanks for your interest in this project. I think you are using a newer version of the `pychromecast` library then initially was used when developing. I don't know the exact requirements anymore but you should find it in some release of pychromecast. Search for a version that uses `get_chromecast` and then install that version using pip. I hope this will solve your issue!
